name: Publish to JSR

on:
    push:
        tags:
            - '*.*.*'

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v6

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: 2.8.0

            - name: Deno CI
              run: deno ci

            - name: Run linter
              run: deno task lint

            - name: Run tests
              run: deno task test

            - name: Publish package
              run: deno publish
